### PR TITLE
create west.yml

### PR DESCRIPTION
**Pull request by DhruvaG2000**
This file can be used to directly pull and use this module. Main use case at the moment is to easily pull this module in a docker container and then run a simple sample build test to see if code compiles without errors.

Furthermore this PR also contains a Dockerfile that can be  used locally as well as in CI/CD workflows.

Signed-off-by: Dhruva Gole <goledhruva@gmail.com>

### CODE REVIEW

**Review by beriberikix — APPROVED** [review]
I followed Dhruva's instructions from Discord:
```
To test it, just run Run west init -m https://github.com/DhruvaG2000/arduino-core-testing.git from your zephyrproject directory 
```
And can verify it initialized a workspace with Arduino module. I did not test it any further.

**Comment by beriberikix** [comment]
Thanks for sharing the testing instructions over Discord! In the future, when it is less obvious how to test a PR, please try to include test instructions for reviewers in the original PR. We're less familiar with your code than you are, and it makes everyone's lives easier :)

**Comment by DhruvaG2000** [comment]
> Thanks for sharing the testing instructions over Discord! In the future, when it is less obvious how to test a PR, please try to include test instructions for reviewers in the original PR. We're less familiar with your code than you are, and it makes everyone's lives easier :)

Thanks alot for your time to test this @beriberikix . I regret the inconvenience caused, I will try to be more verbose regarding testing instructions from now on.

**Comment by beriberikix** [comment]
No worries at all! I was in the middle of moving so it was hard to contribute without all the details in one place.

Thanks.

**Pull request merged**
