### PR TITLE
feat: add particle xenon pinmap

### PR DESCRIPTION
**Pull request by alvarowolfx**
I changed things so the pinmap file is added depending on the target board.

### CODE REVIEW

**Comment by DhruvaG2000** [comment]
If there will be many more supported boards in the future, perhaps we should consider making a folder `cores/arduino/pinmaps/` that will include all the files like `particle_xenon_pinmap.h`. This will make the directory structure a bit more cleaner Imo.

**Comment by beriberikix** [comment]
I recommend we follow the Arduino conventions and put different board in a [`variants` folder](https://github.com/arduino/ArduinoCore-mbed/tree/master/variants). It's not critical now but will be useful in the future when we want to integrate with the Arduino IDE, see the [platform specification](https://arduino.github.io/arduino-cli/0.24/platform-specification/#core-variants).

**Comment by beriberikix** [comment]
@alvarowolfx when you get a chance can you adapt the implementation to the new structure?

**Comment by DhruvaG2000** [comment]
> @alvarowolfx when you get a chance can you adapt the implementation to the new structure?

+1 
This would really help us from a new user perspective to understand difficulties that adding a new board may bring on table.

**Pull request closed without merging**
