### PR TITLE
Add micros() and millis() functions

### PR DESCRIPTION
**Pull request by szczys**
Wraps Zephyr kernel timing calls in Arduino API. This completes the Arduino Time functions.

### CODE REVIEW

**Comment by DhruvaG2000** [comment]
Could we perhaps add a sample to demonstrate this? I'll add it if the consensus is yes..
Otherwise this LGTM
Haven't got the chance to test it but it looks alright to me.

**Comment by szczys** [comment]
These are standard Arduino functions. I tested them by adding this inside the loop of blinky_arduino:

```
printk("micros: %ld", micros());
printk("millis: %ld", millis());
```

My feeling is that they don't really belong in the blinky sample. We could do a "kitchen sink" sample that demonstrates everything. Or maybe some type of test app for that purpose?

**Comment by DhruvaG2000** [comment]
Or else I feel we shouldn't over do on the samples either, I think these are pretty simple and standard in the arduino docs and any user can just google it and get to know how it is used

**Review by DhruvaG2000 — APPROVED** [review]
LGTM, Merging into dev

**Pull request merged**
