### PR TITLE
Create common digital pin definition

### PR DESCRIPTION
**Pull request by soburi**
The digitalPins enumeration, arduino_pins array,
and contents of these are determined by d[N]_gpios declaration in dts.

Interlock the declaration with the dts definition.

### CODE REVIEW

**Comment by DhruvaG2000** [comment]
Thank you for your contribution!
Please rebase your branch on latest main

**Comment by soburi** [comment]
Hi, @DhruvaG2000 
> Thank you for your contribution! Please rebase your branch on latest main and resolve conflicts

Rebase done.

**Review by DhruvaG2000 — CHANGES_REQUESTED** [review]
Tested on arduino nano 33 ble sense, and arduino mkr zero and blink LEDs work okay.
Thanks @soburi this looks much more elegant! Thanks to macro magic I guess ;) 

This PR is ready to merge pending a few formatting issues:
```
ERROR: space prohibited before that close parenthesis ')'
#498: FILE: variants/variants.h:22:
```
and many more that appear upon running ``checkpatch.pl patches/0001-variants-Define-common-digital-pin-definition.patch``

**Comment by soburi** [comment]
> Tested on arduino nano 33 ble sense, and arduino mkr zero and blink LEDs work okay. Thanks @soburi this looks much more elegant! Thanks to macro magic I guess ;)
> 
> This PR is ready to merge pending a few formatting issues:
> 
> ```
> ERROR: space prohibited before that close parenthesis ')'
> #498: FILE: variants/variants.h:22:
> ```
> 
> and many more that appear upon running `checkpatch.pl patches/0001-variants-Define-common-digital-pin-definition.patch`

Update done. I'll also update other PRs. Thanks.

**Comment by soburi** [comment]
> Tested on arduino nano 33 ble sense, and arduino mkr zero and blink LEDs work okay.
> Thanks @soburi this looks much more elegant! Thanks to macro magic I guess ;)

I think typically configuration must be able to handle without an additional header, only an overlay file.
In other words, We should create a header file only case if it can't derive from devicetree information.

(It is painful for us to manage many files and various rules.
We should make effort to only need to write an overlay file basically.)

**Comment by DhruvaG2000** [comment]
@soburi your arduino nano 33 iot fix is merged, there seem to be minor conflicts, kindly resolve them

**Review by DhruvaG2000 — APPROVED** [review]
Built and tested locally, also tried blinky samples on nano 33 ble sense and mkrzero. Seem to work.
Thanks alot for your contributions @soburi !

**Pull request merged**
