### PR TITLE
Fix/samples/cmakelists

### PR DESCRIPTION
**Pull request by DhruvaG2000**

### CODE REVIEW

**Review by szczys — CHANGES_REQUESTED** [review]
Wow! This is great work. I'm really interested to hear how you got the `$ZEPHYR_BASE` part of this to work since I don't see it set in my ENV.

Compilation works worked for me after I tweaked directory names, I suggest the following changes should be included in this PR:

* The directories in the variants folder should be renamed to all lower-case
* CMakeLists.c files in all samples should be changed to match changes made in this PR (hello-arduino)

This is a giant improvement, nice job!

**Comment by beriberikix** [comment]
Is this ready for review? If so, let's take it out of draft!

**Comment by DhruvaG2000** [comment]
> Is this ready for review? If so, let's take it out of draft!

I am not able to rename all the folder names for some reason, just some issue with windows or something I guess...

**Comment by DhruvaG2000** [comment]
Have to make all the folder names from caps to small case

**Review by szczys — APPROVED** [review]
LGTM!

**Comment by DhruvaG2000** [comment]
Merging to dev since I have @szczys approval!

**Pull request merged**
