### PR TITLE
Split Nano 33 BLE & Nano 33 BLE Sense

### PR DESCRIPTION
**Pull request by beriberikix**

### CODE REVIEW

**Comment by DhruvaG2000** [comment]
I think we can then remove ``ARDUINO_NANO33BLE`` from variants as well ...
This will ofcourse require a path change across the CMakelists in all the samples as well.

**Comment by DhruvaG2000** [comment]
Just tried building both nano ble and sense and both build fine! Without any changes in any cmakelists!

So I guess this PR LGTM

**Comment by beriberikix** [comment]
Great! But let me make those changes anyway before merging 👍

**Review by DhruvaG2000 — APPROVED** [review]
Built and tested both variants, ``arduino_nano_33_ble_sense`` and ``arduino_nano_33_ble`` and since they pretty much have the same pin out, the examples worked just fine.
IMO this PR can be merged to dev.

**Comment by DhruvaG2000** [comment]
> Great! But let me make those changes anyway before merging

yes, otherwise the samples may break.

**Pull request merged**
